import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "./components/Navbar";
import Banner from "./components/Banner";
import { sanityClient, urlFor } from "../sanity";
import { Post } from "@/type";
import Link from "next/link";

interface props {
  data: [Post];
}
const inter = Inter({ subsets: ["latin"] });

export default function Home({ data }: props) {
  console.log(data);
  return (
    <>
      <Head>
        <title>Medium Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Navbar />
        <Banner />
      </main>
      <div className="grid grid-col-1 gap-3 p-2  sm:grid-cols-2 md:p-7 lg:grid-cols-3 xl:w-4/5 mx-auto">
        {data.map((e) => {
          return (
            <Link href={`post/${e.slug.current}`} key={e._id}>
              <div className="group cursor-pointer h-96 border rounded-lg overflow-hidden">
                {e.mainImage && (
                  <Image
                    src={urlFor(e.mainImage).url()}
                    className="w-full h-60 object-cover group-hover:scale-105 transition-all duration-50 ease-in-out"
                    width={300}
                    height={300}
                  />
                )}
                <div className="flex justify-between p-5">
                  <div>
                    <p className="text-m font-bold">
                      {e.title} by {e.author.name}
                    </p>
                    <p className="text-sm w-5/6">{e.description}</p>
                  </div>
                  <Image
                    className="w-12 h-12 rounded-full"
                    src={urlFor(e.author.image).url()}
                    width={300}
                    height={300}
                  />
                </div>
              </div>
            </Link>
          );
        })}
      </div>
    </>
  );
}

export const getServerSideProps = async () => {
  const query = `
  *[_type=="post"]{
    _id,
    title,
    author->{name,image},
    description,
    mainImage,
    publishedAt,
    slug,
    body
  }`;
  const posts = await sanityClient.fetch(query);
  return {
    props: {
      data: posts,
    },
  };
};
